### ISSUE TITLE
Error due to incorrect dependency update after plugin deletion

### ISSUE THREAD

**Issue by guqing** [pf4j/pf4j#576]
### Description
While managing plugins with p4fj, I encountered an issue where the dependency relationship of a deleted plugin was not correctly updated. Specifically, after deleting a plugin that other plugins depend on, attempting to stop those dependent plugins results in an error, stating `Plugin 'hello-plugin' not found`, despite `hello-plugin` having been deleted.

### Steps to Reproduce
1. Assume there are two plugins: one named `welcome-plugin` and another named `hello-plugin`, with `hello-plugin` depending on `welcome-plugin`.
2. Start all plugins.
3. Stop and delete the `hello-plugin`:
   ```java
   pluginManager.stopPlugin("hello-plugin");
   pluginManager.deletePlugin("hello-plugin");
   ```
4. Then, stop the `welcome-plugin`.

### Expected Behavior
After `hello-plugin` has been deleted, `welcome-plugin` should stop without any errors, unaffected by any dependency issues.

### Actual Behavior
When attempting to stop `welcome-plugin`, the error `Plugin 'hello-plugin' not found` occurs. This error is due to the plugin manager's `dependencyResolver` still referencing the uninstalled `hello-plugin`.

### Dependency Graphs
- `dependenciesGraph`:
   ```
   welcome-plugin -> []
   hello-plugin -> [welcome-plugin]
   ```
- `dependentsGraph`:
   ```
   welcome-plugin -> [hello-plugin]
   hello-plugin -> []
   ```

### Possible Solution
Update the dependency graphs upon plugin deletion to ensure all dependencies and dependents are correctly handled.

### Environment Information

v3.11.0

If I have misunderstood, please correct me 🫡

**Comment by decebals** [comment]
Thank you for your detailed description.
I will investigate.
A unit test that highlighted the problem simplifies the investigation.

**Comment by decebals** [comment]
@guqing  It was a miscommunication on my part. The bug was fixed very soon after the problem was reported and is already available in version 3.11.1

**Comment by decebals** [comment]
@guqing And by the way, do you have any English documentation for Halo? :smile: 
I'm trying to understand what Halo does and I can't find documentation in English.

**Comment by guqing** [comment]
> @guqing And by the way, do you have any English documentation for Halo? 😄 I'm trying to understand what Halo does and I can't find documentation in English.

Thank you very much for your effort ♥️ in developing such an excellent Java plugin framework, p4fj 🫡. Currently, Halo is primarily targeted at Chinese users, so we have not provided an English documentation yet. However, the Halo application does include some internationalized English translations. We may consider offering more in the future. If you're interested, you could use GPT to translate the documents for now 😅. Here is the user guide for Halo: https://docs.halo.run/user-guide/common and here is a link to a demonstration video: [Watch Now](https://www.bilibili.com/video/BV15x4y1U7RU/?share_source=copy_web&vd_source=a1f8493fdda0f157a104b52ad7c7dd15) 🤠

**Comment by guqing** [comment]
> @guqing It was a miscommunication on my part. The bug was fixed and is already available in version 3.11.1

Hi @decebals ，I checked version 3.11.1 and it doesn't seem to include a fix for this issue,please see [compared with release-3.11.0...release-3.11.1](https://github.com/pf4j/pf4j/compare/release-3.11.0...release-3.11.1). 
I also tried it, and the issue still persists. One related change is [74aa987](https://github.com/pf4j/pf4j/commit/74aa987ca9a23234efbd58766d648135af7bdcc7), but it only includes some test classes. 
Additionally, there's a related PR that is still open: [#579](https://github.com/pf4j/pf4j/pull/579).

**Comment by decebals** [comment]
https://github.com/pf4j/pf4j/commit/1a16be8ad024d3c5fac380ec819bf6e17644c375

**Comment by guqing** [comment]
> [1a16be8](https://github.com/pf4j/pf4j/commit/1a16be8ad024d3c5fac380ec819bf6e17644c375)

yeah I am aware of this PR. I believe you might have forgotten to include this fix in version 3.11.1. I suggest taking a detailed look at [this comparison](https://github.com/pf4j/pf4j/compare/release-3.11.0...release-3.11.1). You mentioned that it was already effective in 3.11.1. Please correct me if I am mistaken.🫡

**Comment by decebals** [comment]
@guqing please test the new pf4j release with your app

**Comment by JohnNiang** [comment]
Hi @decebals , please check the commit <https://github.com/pf4j/pf4j/commit/74aa987ca9a23234efbd58766d648135af7bdcc7> that is only included unit test code and the PR <https://github.com/pf4j/pf4j/pull/579> that hasn't been merged.

> See https://github.com/pf4j/pf4j/compare/release-3.11.0...release-3.11.1 for more.

**Comment by decebals** [comment]
I understand. I will take a look soon

**Comment by decebals** [comment]
The PR https://github.com/pf4j/pf4j/pull/579 fixes the issue. Please try it to be sure that your problem is solved.

**Comment by decebals** [comment]
The fix is available in the latest release (3.12.0).

**Comment by guqing** [comment]
> The fix is available in the latest release (3.12.0).

Thank you very much for your effort ♥️
